### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by Jonesyj83** [Lokraan/Hasami#19]
Been trying to get this setup without any luck. every time I start the bot I get.
`discord@static:~/SignalBot/Hasami-master$ python3.6 main.py 
[2018-05-25 12:08:49] [INFO  ] root: Set up database
[2018-05-25 12:08:49] [INFO  ] discord.client: logging in using static token
[2018-05-25 12:08:49] [INFO  ] discord.gateway: Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6&compress=zlib-stream
[2018-05-25 12:08:49] [INFO  ] discord.gateway: Shard ID None has sent the IDENTIFY payload.
[2018-05-25 12:08:49] [INFO  ] discord.gateway: Shard ID None has connected to Gateway: gateway-prd-main-gngd, discord-sessions-prd-1-20 (Session ID: cd3726c2402de937133aefc43c1c772b).
[2018-05-25 12:08:51] [INFO  ] root: logged in as The King's Hand - Signals
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "main.py", line 68, in on_ready
    await bot.start()
  File "/home/discord/SignalBot/Hasami-master/bot.py", line 58, in start
    await self._initialize_checker()
  File "/home/discord/SignalBot/Hasami-master/bot.py", line 130, in _initialize_checker
    for server in self._client.servers:
AttributeError: 'Client' object has no attribute 'servers'
[2018-05-25 12:08:51] [INFO  ] root: Setting market cap $332,932,811,646.00
[2018-05-25 12:08:51] [ERROR ] asyncio: Task exception was never retrieved
future: <Task finished coro=<Hasami._set_playing_status() done, defined at /home/discord/SignalBot/Hasami-master/bot.py:63> exception=TypeError("change_presence() got an unexpected keyword argument 'game'",)>
Traceback (most recent call last):
  File "/home/discord/SignalBot/Hasami-master/bot.py", line 82, in _set_playing_status
    game=discord.Game(name=mc))
TypeError: change_presence() got an unexpected keyword argument 'game'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "main.py", line 73, in on_message
    await message_processor.process_message(message)
  File "helpers/message_processor.py", line 71, in process_message
    server_id = message.server.id
AttributeError: 'Message' object has no attribute 'server'
`

What needs to be done?

**Comment by Lokraan** [comment]
https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.server

**Comment by Jonesyj83** [comment]
Yeah removed it and readded to make sure.  Still same error. 
When I invite the bot to my server it doesn't add server I'd or name into the db. But when it leaves a server it says left unknown guild. 
Could this be a reason?

**Comment by Lokraan** [comment]
I don't think so but honestly my bot is a mess right now and I'm working on other projects. I will probably return to this bot in the future but I do not currently have time to fix the many issues that plague it. 

This is a really nice bot that includes price functionality: https://github.com/Abolah/Coinbot

**Comment by Jonesyj83** [comment]
no worries cheers anyway maybe try it on another computer. Got other bots running so not sure what the issue is.
