### ISSUE TITLE
New update issue

### ISSUE THREAD

**Issue by haxxus** [Lokraan/Hasami#8]
Hello :) looking forward to testing this new update , i'm a bit confused i should run main.py correct? If so i did and i see only:

Logged in

when i enter $start on discord i get the response  Starting @MyDiscordName , but nothing happens after nor over in ssh is stuck there on Logged in, also when i try $greet i get:

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "hasami.py", line 33, in on_message
    await bot.greet(message)
AttributeError: module 'bot' has no attribute 'greet'


```

( i renamed main to hasami )

**Comment by Lokraan** [comment]
Sorry, it's because "bot" references the module itself. It also takes ~1 minute for the responses to start coming through after you type $start.

**Comment by haxxus** [comment]
Great yes greet works now , but ive had it on for over 20 minutes and no responses so far umm

**Comment by haxxus** [comment]
ah ok i actually just got in some errors


```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "hasami.py", line 44, in on_message
    await b.start_checking_markets(message)
  File "/home/Hasami-master/bot.py", line 372, in start_checking_markets
    await self.check_markets()
  File "/home/Hasami-master/bot.py", line 347, in check_markets
    outputs, price_updates["Bittrex"] = await self._check_bittrex_markets(session)
  File "/home/Hasami-master/bot.py", line 311, in _check_bittrex_markets
    out = await self._process_market ( session, info )
  File "/home/Hasami-master/bot.py", line 165, in _process_market
    rsi = await self._calc_rsi(session, name)
  File "/home/Hasami-master/bot.py", line 201, in _calc_rsi
    history = json.loads( await self._get_market_history ( session, market, self._rsi_tick_interval ) )
  File "/home/Hasami-master/bot.py", line 98, in _get_market_history
    return await resp.text()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 764, in text
    yield from self.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 739, in read
    self._content = yield from self.content.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 518, in wrapper
    result = yield from func(self, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 583, in read
    return (yield from super().read(n))
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 290, in read
    block = yield from self.readany()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 518, in wrapper
    result = yield from func(self, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 593, in readany
    return (yield from super().readany())
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 307, in readany
    yield from self._wait('readany')
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 224, in _wait
    yield from waiter
aiohttp.errors.ServerDisconnectedError
```
