### ISSUE TITLE
Ignoring exception in on_message

### ISSUE THREAD

**Issue by haxxus** [Lokraan/Hasami#9]
not sure if you see messages from closed errors so here is whats happening, this comes up after about 10-20 minutes after $start 

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "hasami.py", line 44, in on_message
    await b.start_checking_markets(message)
  File "/home/Hasami-master/bot.py", line 372, in start_checking_markets
    await self.check_markets()
  File "/home/Hasami-master/bot.py", line 347, in check_markets
    outputs, price_updates["Bittrex"] = await self._check_bittrex_markets(session)
  File "/home/Hasami-master/bot.py", line 311, in _check_bittrex_markets
    out = await self._process_market ( session, info )
  File "/home/Hasami-master/bot.py", line 165, in _process_market
    rsi = await self._calc_rsi(session, name)
  File "/home/Hasami-master/bot.py", line 201, in _calc_rsi
    history = json.loads( await self._get_market_history ( session, market, self._rsi_tick_interval ) )
  File "/home/Hasami-master/bot.py", line 98, in _get_market_history
    return await resp.text()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 764, in text
    yield from self.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 739, in read
    self._content = yield from self.content.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 518, in wrapper
    result = yield from func(self, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 583, in read
    return (yield from super().read(n))
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 290, in read
    block = yield from self.readany()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 518, in wrapper
    result = yield from func(self, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 593, in readany
    return (yield from super().readany())
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 307, in readany
    yield from self._wait('readany')
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 224, in _wait
    yield from waiter
aiohttp.errors.ServerDisconnectedError
```

**Comment by Lokraan** [comment]
Sorry, I'm currently at work, I'll be able to get to it in ~7 hours.

**Comment by haxxus** [comment]
Great :)

**Comment by Lokraan** [comment]
Is the bot able to print updates on your end?

**Comment by Lokraan** [comment]
Even if the exception occurs, the bot should continue to run. 

I'm also adding an option for the price updates generated to be logged soon, should be out by tomorrow.

**Comment by haxxus** [comment]
Morning , will update and test soon. Are you using it on discord channel ? I'm slowly building one with tools and the structure to teach/guide users starting out on crypto trading or even the more experienced.
Your welcome to be part of it, no commitments you can do as you wish, your tool has its own channel i really love it.

**Comment by haxxus** [comment]
Ok just ran it , well right now i have not gotten the error but is been over 15 minutes no messages, umm i gave it all permissions to the channel id its under ( not admin ) but everything else is enabled .

**Comment by Lokraan** [comment]
Could you send me your config file and the link to the discord please?

**Comment by haxxus** [comment]
https://discord.gg/7BkRkR ill send you config there :)
